### ISSUE TITLE
Can't build for Elasticsearch 7.5.0

### ISSUE THREAD

**Issue by gtsoukas** [o19s/elasticsearch-learning-to-rank#261] opened 2019-12-09 08:14 UTC
Could you please advise me how to build for Elasticsearch 7.5.0?

Here is what I tried:
```
docker run -it \
  docker.elastic.co/elasticsearch/elasticsearch:7.5.0 /bin/bash

yum -y update
yum -y install ca-certificates wget unzip git

export JAVA_HOME=/usr/share/elasticsearch/jdk/

cd /tmp
git clone https://github.com/o19s/elasticsearch-learning-to-rank
cd elasticsearch-learning-to-rank

# changing to newer gradle version in order to avoid "java.lang.IllegalArgumentException: Unsupported class file major version 57"
sed -i 's/gradle-5\.5\.1/gradle-6\.0\.1/g' gradle/wrapper/gradle-wrapper.properties

sed -i 's/7\.3\.1/7\.5\.0/g' build.gradle

./gradlew clean check
```
Error:
```
Downloading https://services.gradle.org/distributions/gradle-6.0.1-bin.zip
..........................................................................................

Welcome to Gradle 6.0.1!

Here are the highlights of this release:
 - Substantial improvements in dependency management, including
   - Publishing Gradle Module Metadata in addition to pom.xml
   - Advanced control of transitive versions
   - Support for optional features and dependencies
   - Rules to tweak published metadata
 - Support for Java 13
 - Faster incremental Java and Groovy compilation
 - New Zinc compiler for Scala
 - VS2019 support
 - Support for Gradle Enterprise plugin 3.0

For more details see https://docs.gradle.org/6.0.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':thirdPartyAudit'.
> Could not resolve all files for configuration ':runtime'.
   > Could not find com.o19s:RankyMcRankFace:0.1.1.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/o19s/RankyMcRankFace/0.1.1/RankyMcRankFace-0.1.1.pom
       - https://artifacts.elastic.co/downloads/elasticsearch/RankyMcRankFace-0.1.1.xml
       - https://artifacts.elastic.co/maven/com/o19s/RankyMcRankFace/0.1.1/RankyMcRankFace-0.1.1.pom
       - https://repo.maven.apache.org/maven2/com/o19s/RankyMcRankFace/0.1.1/RankyMcRankFace-0.1.1.pom
       - file:/root/.m2/repository/com/o19s/RankyMcRankFace/0.1.1/RankyMcRankFace-0.1.1.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 48s

```

**Comment by softwaredoug** [comment] 2019-12-12 20:01
Hi @gtsoukas, I wouldn't expect it to build for 7.5, we need to upgrade the code to be compatible. Of course any help along those lines very welcome. There's a PR in progress for 7.4 which is a prerequisite.

**Comment by softwaredoug** [comment] 2019-12-12 20:02
Closing as duplicate of #260

**Closed by softwaredoug** 2019-12-12 20:02 UTC

**Comment by gtsoukas** [comment] 2019-12-13 10:39
@softwaredoug thanks a lot for the feedback and your awesome work!
