### ISSUE TITLE
When requesting with LTR rescore, the response speed is very slow, the requst cache of elasticsearch dose not work

### ISSUE THREAD

**Issue by li910802** [o19s/elasticsearch-learning-to-rank#177] opened 2018-08-08 06:19 UTC
There are 4 nodes in our cluster, 10G for each node, our sever has 64 kernels.
The featureset has about 10 features, the LTR model has 100 trees and the depth is 3. 
We need to rescore and log features at the same time. The rescore window_size is set to 60.
We run a stress testing, the qps is about 500 per second, the average respond time is about 250ms. 

We debug the code src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java:

```
protected RankerQuery doToQuery(QueryShardContext context) throws IOException {
        String indexName = storeName != null ? IndexFeatureStore.indexName(storeName) : IndexFeatureStore.DEFAULT_STORE;
        FeatureStore store = storeLoader.load(indexName, context.getClient());
        LtrQueryContext ltrQueryContext = new LtrQueryContext(context,
activeFeatures == null ? Collections.emptySet() : new HashSet<>(activeFeatures));
```
when `context.getClient()` method called , the request cache will be set to disabled. 
Is there any way to improve the response speed?

**Comment by nomoa** [comment] 2018-08-20 09:38
Hi,
10 features with 100 trees and a max depth of 3 seems unlikely to cause per issue by itself.
I'd look into other aspects of the whole query:
- what about the filter query itself
- rescoring and logging at the same time involves a cost, it'll to extract feature vectors twice. If you can afford it it's fine, if not you'll have to run feature collection offline.
- individual feature queries may be slow have you tried to profile them individually?

As for the request cache, yes it's disabled because of the getClient() call, but I doubt this is the main cause of your problem here (the request cache is disabled in many differents situations). If you still believe that request cache can help your usecase you could add a cache layer between elastic and your client.
I think it's fair to disable the request cache if the client is being accessed, I could see some optimizations here (only call getClient when needed) but not sure that will help much...

**Comment by li910802** [comment] 2018-08-23 07:33
Sorry to reply late. According to the different query circumstances mentioned above, we run different stress testings:
- query without rescoring or logging features
Requests per second:    1347.18 [#/sec] (mean)
Time per request:       74.229 [ms] (mean)

- query with rescoring and logging features
Requests per second:    421.51 [#/sec] (mean)
Time per request:       237.244 [ms] (mean)

- query only with rescoring
Requests per second:    533.47 [#/sec] (mean)
Time per request:       187.452 [ms] (mean)

- query only with logging features
Requests per second:    660.92 [#/sec] (mean)
Time per request:       151.305 [ms] (mean)

**Comment by nomoa** [comment] 2018-08-23 08:09
I don't have strong suggestions to make except continuing to investigate if there's a perf bottleneck you could unlock, if you don't derived_expression you could enable the elastic [profiling](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-profile.html) APIs to see if there is a particular feature that's more costly than others?

The numbers you presented seems coherent, for a very simple model logging and ranking should be quite equivalent, logging features is faster (~36ms faster, 36ms to run 100 simple trees over 60 results seems slow): did you request the same number of hits than the rescore window size when doing logging only?

**Comment by softwaredoug** [comment] 2018-09-23 01:48
@li910802 did anything come of this investigation?

**Comment by li910802** [comment] 2018-09-25 08:28
When the match_phrase query of similarity features replaced by the match query , the requests will get faster, but still very slow.

**Comment by li910802** [comment] 2018-09-25 09:28
OK, I can sent my ltr featureset and rescore query dsl to your email address later.

**Comment by softwaredoug** [comment] 2018-09-27 16:48
One way to isolate LTR vs the features is to run all your features in a boolean query (one big should array). If those are fast, it seems to point at the LTR plugin. If they are slow, it would seem to point at the speed of the queries themselves

**Comment by li910802** [comment] 2018-09-28 06:32
We compared two stress tests and the only difference between the two tests is that one test adds logging 6 features on the basis of the other. Each feature is to get the field value, just like below:
‘’‘
"template": {
   "function_score": {
	"field_value_factor": {
		"field": "new",
		"missing": 0
	}
   }
}
‘’’
The result is that the query with logging features is 50% slower then the other. 
We wonder if too many function_score queries cause the loss of query speed. The features of bm25 similarity may be more costly.
When using LTR model to rescore, the features of same queries are the same, is there any request cache mechanism to cache the same features to avoid repeated queries?

**Comment by li910802** [comment] 2018-09-29 09:37
@softwaredoug According to your advice, we run two different stress tests, one test combined all the features in a big boolean query, the other seperated the features. The result is that all of the tests are slow and the test with only one combined feature is a little bit slower.

**Comment by softwaredoug** [comment] 2018-11-12 14:30
Hey @li910802 I would suggest moving this question to [slack](http://o19s.com/slack) to see if we could help you. Right now I think the issue is the performance of one of your features, not the plugin itself

**Closed by softwaredoug** 2018-11-12 14:30 UTC
