### ISSUE TITLE
Search Keyword with certain conditions 

### ISSUE THREAD

**Issue by anshukpal** [o19s/elasticsearch-learning-to-rank#474] opened 2023-10-13 03:59 UTC
When we are searching just plain search across all components, it's all fine. Lets we search keyword "2139", same is used in sltr params keyword for logfeatures and ltr search.

Now the need of the search keyword, will be a more complicated and will search find across specific fields. 
The search keyword would need to run across certain fields (some of which are features if not all) and the search condition would be required how the search need to happen.

The normal search which works fine would be:

```
{
    "size": 25,
    "from": 0,
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "query": "*2139*",
                        "fields": [
                            "field1^9",
                            "field1.inString^7",
                            "field2",
                            "field2.startsWith"
                        ],
                        "lenient": true,
                        "analyze_wildcard": true,
                        "fuzzy_prefix_length": 2
                    }
                }
            ],
            "filter": [
                {
                    "terms": {
                        "field3.raw": [
                            "22222"
                        ]
                    }
                }
            ]
        }
    },
    "_source": {
        "includes": ["*"
        ]
    }
}

```
We have been defined features, three features for field1 and field2, field3. 

So to handle this kind of search:

- How do we handle this and have this added in logfeatures and ltr search?
- Now the featureset defined is a simple one, do we need to change that?

**Comment by wrigleyDan** [comment] 2023-11-24 12:55
Based on my understanding of your question this should be perfectly able with the plugin.

I did a quick test with the [hello-ltr repository](https://github.com/o19s/hello-ltr) (specifically the notebook `notebooks/elasticsearch/tmdb/netfix movies.ipynb`) and created a featureset with the following code

```
config = {
           "featureset": {
            "features": [
                { #1
                    "name": "my_feature",
                    "params": ["keywords"],
                    "template": {
                        "bool": {
                            "must": [
                                {
                                    "query_string": {
                                        "query": "{{keywords}}",
                                        "fields": [
                                            "cast^9",
                                            "title^7",
                                            "tagline",
                                            "overview"
                                        ],
                                        "lenient": True,
                                        "analyze_wildcard": True,
                                        "fuzzy_prefix_length": 2
                                    }
                                }
                            ],
                            "filter": [
                                {
                                    "terms": {
                                        "title": [
                                            "star"
                                        ]
                                    }
                                }
                            ]
                        }  
                    }
                }            
            ]
        }
}


client.create_featureset(index='tmdb', name='title', ftr_config=config)
```

The fields I am using are the ones I had in the example index. You would need to replace the fields with your fields. After you have your featureset created you can log the feature scores in the usual way. For examples you can either look into the docs or the above mentioned Jupyter notebook.

Here's an example for one query:

```
POST tmdb/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "terms": {
            "_id": [
              "11",
              "85783",
              "7555",
              "1370",
              "1369"
            ]
          }
        },
        {
          "sltr": {
            "_name": "logged_featureset",
            "featureset": "title",
            "params": {
              "keywords": "star"
            }
          }
        }
      ]
    }
  },
  "ext": {
    "ltr_log": {
      "log_specs": {
        "name": "log_entry1",
        "named_query": "logged_featureset"
      }
    }
  }
}

```

In the response you then get the logged features.

Let me know how that helps or I misunderstood your question.

**Comment by wrigleyDan** [comment] 2024-01-17 09:34
Closing this assuming the issue is resolved with the latest comment.

**Closed by wrigleyDan** 2024-01-17 09:34 UTC
